const FLAG_BASE_URL = 'https://flagcdn.com/w160';

const COUNTRY_ROWS = [
  ['Afghanistan', '아프가니스탄', 'AFG', 'af'],
  ['Albania', '알바니아', 'ALB', 'al'],
  ['Algeria', '알제리', 'ALG', 'dz'],
  ['American Samoa', '아메리칸사모아', 'ASA', 'as'],
  ['Andorra', '안도라', 'AND', 'ad'],
  ['Angola', '앙골라', 'ANG', 'ao'],
  ['Anguilla', '앵귈라', 'AIA', 'ai'],
  ['Antigua and Barbuda', '앤티가 바부다', 'ATG', 'ag'],
  ['Argentina', '아르헨티나', 'ARG', 'ar'],
  ['Armenia', '아르메니아', 'ARM', 'am'],
  ['Aruba', '아루바', 'ARU', 'aw'],
  ['Australia', '호주', 'AUS', 'au'],
  ['Austria', '오스트리아', 'AUT', 'at'],
  ['Azerbaijan', '아제르바이잔', 'AZE', 'az'],
  ['Bahamas', '바하마', 'BAH', 'bs'],
  ['Bahrain', '바레인', 'BHR', 'bh'],
  ['Bangladesh', '방글라데시', 'BAN', 'bd'],
  ['Barbados', '바베이도스', 'BRB', 'bb'],
  ['Belarus', '벨라루스', 'BLR', 'by'],
  ['Belgium', '벨기에', 'BEL', 'be'],
  ['Belize', '벨리즈', 'BLZ', 'bz'],
  ['Benin', '베냉', 'BEN', 'bj'],
  ['Bermuda', '버뮤다', 'BER', 'bm'],
  ['Bhutan', '부탄', 'BHU', 'bt'],
  ['Bolivia', '볼리비아', 'BOL', 'bo'],
  ['Bosnia and Herzegovina', '보스니아 헤르체고비나', 'BIH', 'ba'],
  ['Botswana', '보츠와나', 'BOT', 'bw'],
  ['Brazil', '브라질', 'BRA', 'br'],
  ['British Virgin Islands', '영국령 버진아일랜드', 'VGB', 'vg'],
  ['Brunei Darussalam', '브루나이', 'BRU', 'bn'],
  ['Bulgaria', '불가리아', 'BUL', 'bg'],
  ['Burkina Faso', '부르키나파소', 'BFA', 'bf'],
  ['Burundi', '부룬디', 'BDI', 'bi'],
  ['Cambodia', '캄보디아', 'CAM', 'kh'],
  ['Cameroon', '카메룬', 'CMR', 'cm'],
  ['Canada', '캐나다', 'CAN', 'ca'],
  ['Cape Verde', '카보베르데', 'CPV', 'cv'],
  ['Cayman Islands', '케이맨 제도', 'CAY', 'ky'],
  ['Central African Republic', '중앙아프리카공화국', 'CTA', 'cf'],
  ['Chad', '차드', 'CHA', 'td'],
  ['Chile', '칠레', 'CHI', 'cl'],
  ['China PR', '중국', 'CHN', 'cn'],
  ['Chinese Taipei', '대만', 'TPE', 'tw'],
  ['Colombia', '콜롬비아', 'COL', 'co'],
  ['Comoros', '코모로', 'COM', 'km'],
  ['Congo', '콩고', 'CGO', 'cg'],
  ['Cook Islands', '쿡 제도', 'COK', 'ck'],
  ['Costa Rica', '코스타리카', 'CRC', 'cr'],
  ['Croatia', '크로아티아', 'CRO', 'hr'],
  ['Cuba', '쿠바', 'CUB', 'cu'],
  ['Curacao', '퀴라소', 'CUW', 'cw'],
  ['Cyprus', '키프로스', 'CYP', 'cy'],
  ['Czech Republic', '체코', 'CZE', 'cz'],
  ['Denmark', '덴마크', 'DEN', 'dk'],
  ['Djibouti', '지부티', 'DJI', 'dj'],
  ['Dominica', '도미니카', 'DMA', 'dm'],
  ['Dominican Republic', '도미니카공화국', 'DOM', 'do'],
  ['DR Congo', '콩고민주공화국', 'COD', 'cd'],
  ['Ecuador', '에콰도르', 'ECU', 'ec'],
  ['Egypt', '이집트', 'EGY', 'eg'],
  ['El Salvador', '엘살바도르', 'SLV', 'sv'],
  ['England', '잉글랜드', 'ENG', 'gb-eng'],
  ['Equatorial Guinea', '적도 기니', 'EQG', 'gq'],
  ['Eritrea', '에리트레아', 'ERI', 'er'],
  ['Estonia', '에스토니아', 'EST', 'ee'],
  ['Eswatini', '에스와티니', 'SWZ', 'sz'],
  ['Ethiopia', '에티오피아', 'ETH', 'et'],
  ['Faroe Islands', '페로 제도', 'FRO', 'fo'],
  ['Fiji', '피지', 'FIJ', 'fj'],
  ['Finland', '핀란드', 'FIN', 'fi'],
  ['France', '프랑스', 'FRA', 'fr'],
  ['Gabon', '가봉', 'GAB', 'ga'],
  ['Gambia', '감비아', 'GAM', 'gm'],
  ['Georgia', '조지아', 'GEO', 'ge'],
  ['Germany', '독일', 'GER', 'de'],
  ['Ghana', '가나', 'GHA', 'gh'],
  ['Gibraltar', '지브롤터', 'GIB', 'gi'],
  ['Greece', '그리스', 'GRE', 'gr'],
  ['Grenada', '그레나다', 'GRN', 'gd'],
  ['Guam', '괌', 'GUM', 'gu'],
  ['Guatemala', '과테말라', 'GUA', 'gt'],
  ['Guinea', '기니', 'GUI', 'gn'],
  ['Guinea-Bissau', '기니비사우', 'GNB', 'gw'],
  ['Guyana', '가이아나', 'GUY', 'gy'],
  ['Haiti', '아이티', 'HAI', 'ht'],
  ['Honduras', '온두라스', 'HON', 'hn'],
  ['Hong Kong', '홍콩', 'HKG', 'hk'],
  ['Hungary', '헝가리', 'HUN', 'hu'],
  ['Iceland', '아이슬란드', 'ISL', 'is'],
  ['India', '인도', 'IND', 'in'],
  ['Indonesia', '인도네시아', 'IDN', 'id'],
  ['Iran', '이란', 'IRN', 'ir'],
  ['Iraq', '이라크', 'IRQ', 'iq'],
  ['Israel', '이스라엘', 'ISR', 'il'],
  ['Italy', '이탈리아', 'ITA', 'it'],
  ['Ivory Coast', '코트디부아르', 'CIV', 'ci'],
  ['Jamaica', '자메이카', 'JAM', 'jm'],
  ['Japan', '일본', 'JPN', 'jp'],
  ['Jordan', '요르단', 'JOR', 'jo'],
  ['Kazakhstan', '카자흐스탄', 'KAZ', 'kz'],
  ['Kenya', '케냐', 'KEN', 'ke'],
  ['Kosovo', '코소보', 'KOS', 'xk'],
  ['Kuwait', '쿠웨이트', 'KUW', 'kw'],
  ['Kyrgyz Republic', '키르기스스탄', 'KGZ', 'kg'],
  ['Laos', '라오스', 'LAO', 'la'],
  ['Latvia', '라트비아', 'LVA', 'lv'],
  ['Lebanon', '레바논', 'LBN', 'lb'],
  ['Lesotho', '레소토', 'LES', 'ls'],
  ['Liberia', '라이베리아', 'LBR', 'lr'],
  ['Libya', '리비아', 'LBY', 'ly'],
  ['Liechtenstein', '리히텐슈타인', 'LIE', 'li'],
  ['Lithuania', '리투아니아', 'LTU', 'lt'],
  ['Luxembourg', '룩셈부르크', 'LUX', 'lu'],
  ['Macau', '마카오', 'MAC', 'mo'],
  ['Madagascar', '마다가스카르', 'MAD', 'mg'],
  ['Malawi', '말라위', 'MWI', 'mw'],
  ['Malaysia', '말레이시아', 'MAS', 'my'],
  ['Maldives', '몰디브', 'MDV', 'mv'],
  ['Mali', '말리', 'MLI', 'ml'],
  ['Malta', '몰타', 'MLT', 'mt'],
  ['Mauritania', '모리타니', 'MTN', 'mr'],
  ['Mauritius', '모리셔스', 'MRI', 'mu'],
  ['Mexico', '멕시코', 'MEX', 'mx'],
  ['Moldova', '몰도바', 'MDA', 'md'],
  ['Mongolia', '몽골', 'MNG', 'mn'],
  ['Montenegro', '몬테네그로', 'MNE', 'me'],
  ['Montserrat', '몬트세랫', 'MSR', 'ms'],
  ['Morocco', '모로코', 'MAR', 'ma'],
  ['Mozambique', '모잠비크', 'MOZ', 'mz'],
  ['Myanmar', '미얀마', 'MYA', 'mm'],
  ['Namibia', '나미비아', 'NAM', 'na'],
  ['Nepal', '네팔', 'NEP', 'np'],
  ['Netherlands', '네덜란드', 'NED', 'nl'],
  ['New Caledonia', '뉴칼레도니아', 'NCL', 'nc'],
  ['New Zealand', '뉴질랜드', 'NZL', 'nz'],
  ['Nicaragua', '니카라과', 'NCA', 'ni'],
  ['Niger', '니제르', 'NIG', 'ne'],
  ['Nigeria', '나이지리아', 'NGA', 'ng'],
  ['North Korea', '북한', 'PRK', 'kp'],
  ['North Macedonia', '북마케도니아', 'MKD', 'mk'],
  ['Northern Ireland', '북아일랜드', 'NIR', 'gb-nir'],
  ['Norway', '노르웨이', 'NOR', 'no'],
  ['Oman', '오만', 'OMA', 'om'],
  ['Pakistan', '파키스탄', 'PAK', 'pk'],
  ['Palestine', '팔레스타인', 'PLE', 'ps'],
  ['Panama', '파나마', 'PAN', 'pa'],
  ['Papua New Guinea', '파푸아뉴기니', 'PNG', 'pg'],
  ['Paraguay', '파라과이', 'PAR', 'py'],
  ['Peru', '페루', 'PER', 'pe'],
  ['Philippines', '필리핀', 'PHI', 'ph'],
  ['Poland', '폴란드', 'POL', 'pl'],
  ['Portugal', '포르투갈', 'POR', 'pt'],
  ['Puerto Rico', '푸에르토리코', 'PUR', 'pr'],
  ['Qatar', '카타르', 'QAT', 'qa'],
  ['Republic of Ireland', '아일랜드', 'IRL', 'ie'],
  ['Romania', '루마니아', 'ROU', 'ro'],
  ['Russia', '러시아', 'RUS', 'ru'],
  ['Rwanda', '르완다', 'RWA', 'rw'],
  ['Saint Kitts and Nevis', '세인트키츠 네비스', 'SKN', 'kn'],
  ['Saint Lucia', '세인트루시아', 'LCA', 'lc'],
  ['Saint Vincent and the Grenadines', '세인트빈센트 그레나딘', 'VIN', 'vc'],
  ['Samoa', '사모아', 'SAM', 'ws'],
  ['San Marino', '산마리노', 'SMR', 'sm'],
  ['Sao Tome and Principe', '상투메 프린시페', 'STP', 'st'],
  ['Saudi Arabia', '사우디아라비아', 'KSA', 'sa'],
  ['Scotland', '스코틀랜드', 'SCO', 'gb-sct'],
  ['Senegal', '세네갈', 'SEN', 'sn'],
  ['Serbia', '세르비아', 'SRB', 'rs'],
  ['Seychelles', '세이셸', 'SEY', 'sc'],
  ['Sierra Leone', '시에라리온', 'SLE', 'sl'],
  ['Singapore', '싱가포르', 'SGP', 'sg'],
  ['Slovakia', '슬로바키아', 'SVK', 'sk'],
  ['Slovenia', '슬로베니아', 'SVN', 'si'],
  ['Solomon Islands', '솔로몬 제도', 'SOL', 'sb'],
  ['Somalia', '소말리아', 'SOM', 'so'],
  ['South Africa', '남아공', 'RSA', 'za'],
  ['South Korea', '대한민국', 'KOR', 'kr'],
  ['South Sudan', '남수단', 'SSD', 'ss'],
  ['Spain', '스페인', 'ESP', 'es'],
  ['Sri Lanka', '스리랑카', 'SRI', 'lk'],
  ['Sudan', '수단', 'SDN', 'sd'],
  ['Suriname', '수리남', 'SUR', 'sr'],
  ['Sweden', '스웨덴', 'SWE', 'se'],
  ['Switzerland', '스위스', 'SUI', 'ch'],
  ['Syria', '시리아', 'SYR', 'sy'],
  ['Tahiti', '타히티', 'TAH', 'pf'],
  ['Tajikistan', '타지키스탄', 'TJK', 'tj'],
  ['Tanzania', '탄자니아', 'TAN', 'tz'],
  ['Thailand', '태국', 'THA', 'th'],
  ['Timor-Leste', '동티모르', 'TLS', 'tl'],
  ['Togo', '토고', 'TOG', 'tg'],
  ['Tonga', '통가', 'TGA', 'to'],
  ['Trinidad and Tobago', '트리니다드 토바고', 'TRI', 'tt'],
  ['Tunisia', '튀니지', 'TUN', 'tn'],
  ['Turkey', '튀르키예', 'TUR', 'tr'],
  ['Turkmenistan', '투르크메니스탄', 'TKM', 'tm'],
  ['Turks and Caicos Islands', '터크스 케이커스 제도', 'TCA', 'tc'],
  ['Uganda', '우간다', 'UGA', 'ug'],
  ['Ukraine', '우크라이나', 'UKR', 'ua'],
  ['United Arab Emirates', '아랍에미리트', 'UAE', 'ae'],
  ['United States', '미국', 'USA', 'us'],
  ['Uruguay', '우루과이', 'URU', 'uy'],
  ['US Virgin Islands', '미국령 버진아일랜드', 'VIR', 'vi'],
  ['Uzbekistan', '우즈베키스탄', 'UZB', 'uz'],
  ['Vanuatu', '바누아투', 'VAN', 'vu'],
  ['Venezuela', '베네수엘라', 'VEN', 've'],
  ['Vietnam', '베트남', 'VIE', 'vn'],
  ['Wales', '웨일스', 'WAL', 'gb-wls'],
  ['Yemen', '예멘', 'YEM', 'ye'],
  ['Zambia', '잠비아', 'ZAM', 'zm'],
  ['Zimbabwe', '짐바브웨', 'ZIM', 'zw'],
];

export const TODAY_FIXTURE_COUNTRIES = COUNTRY_ROWS.map(([nameEn, nameKo, code, flagCode]) => ({
  nameEn,
  nameKo,
  code,
  flagCode,
  flagUrl: `${FLAG_BASE_URL}/${flagCode}.png`,
  searchText: `${nameKo} ${nameEn} ${code}`.toLowerCase(),
}));

export function getTodayFixtureCountryByCode(code) {
  const normalized = String(code || '').trim().toUpperCase();
  return TODAY_FIXTURE_COUNTRIES.find(country => country.code === normalized) || null;
}
